---
- name: copy cloud confgi
  template: src=cloud_config_install.tmpl dest=/tmp/cloud-config.yaml

- name: debug cloud config
  shell: cat /tmp/cloud-config.yaml


- name: install coreos
  shell: |
     apt-get -y install gawk
     wget https://raw.githubusercontent.com/coreos/init/master/bin/coreos-install -P /tmp
     chmod a+x /tmp/coreos-install
     sed -i '/# inform the OS of partition table changes/a \
     sleep 10 \
     sync' /tmp/coreos-install
     /tmp/coreos-install -d /dev/sda -C {{ coreos_channel }} -c /tmp/cloud-config.yaml

- name: clear osd disk 
  command: dd if=/dev/zero of={{ ceph_osd_device }} bs=512 count=1 conv=notrunc
  when: ceph_osd_device is defined

- name: create new partintion table on osd disk
  shell: |
      echo "g
      w" | fdisk {{ ceph_osd_device }}
  when: ceph_osd_device is defined
  ignore_errors: true

- name: reboot server
  shell: sleep 5 && reboot &
  args:
      executable: /bin/bash
  async: 10
  poll: 0


- name: waiting for server to go down
  local_action: 
      module: wait_for
      host: "{{ inventory_hostname }}"
      port: 22
      delay: 1
      timeout: 20
      state: stopped

- name: waiting for server to come back
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=1
      timeout=200

- name: remove server from local known_hosts file
  local_action: command  /usr/bin/ssh-keygen -R {{ inventory_hostname }}
  ignore_errors: true

