apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph
provisioner: kubernetes.io/rbd
parameters:
  monitors: ceph-mon.ceph.svc.cluster.local:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-system
  pool: rbd
  userId: admin
  userSecretName: ceph-secret
